pipeline {
  agent {
    docker {
      image 'maven:3-alpine'
      args '-v /root/.m2:/root/.m2'
      }
    }
  stages {
    stage('Build') {
      steps {
        sh 'mvn -B -DskipTests clean package'
      }
    }
    stage('Test') { 
      steps {
        sh 'mvn test' 
        }
      }
    stage('Push artifact to Nexus'){
      when { not { expression { return env.BRANCH_NAME.startsWith('PR') } } }
      steps{      nexusArtifactUploader artifacts: [
        [artifactId: 'my-app',
          classifier: 'debug',
          file: 'target/my-app-1.0-SNAPSHOT.jar',
          type: 'jar']
        ], 
        credentialsId: 'nexus_creds', 
        groupId: '228', 
        nexusUrl: 'nexus:8081',
        nexusVersion: 'nexus3', 
        protocol: 'http', 
        repository: 'MyCoolestRepo',
        version: '3.23'
        }
      }
    }
    post {
      always {
        junit 'target/surefire-reports/*.xml' 
      }
    } 
  }